version: '3.9'

services:
  client:
    image: client
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env.development.local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - dev-hype

networks:
  dev-hype:
    driver: bridge
