name: Build Containers for Staging & Push to Dockerhub

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          NEXT_PUBLIC_API_URL: https://staging-api.dev-hype.com/graphql
        with:
          push: true
          tags: devhype/dev-hype-fe:staging
          file: Dockerfile.prod
