name: Build Containers for Prod & Push to Dockerhub

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: http://localhost:8000/graphql
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: devhype/dev-hype-fe:latest
          file: Dockerfile.prod
